DROP TABLE IF EXISTS quizzes CASCADE;

CREATE TABLE quizzes (
  id SERIAL PRIMARY KEY NOT NULL,
  creator_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  type VARCHAR(255) NOT NULL,
  public BOOLEAN NOT NULL DEFAULT TRUE,
  thumbnail_url VARCHAR(255) NOT NULL
);
