DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS quizzes CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS results CASCADE;
DROP TABLE IF EXISTS quiz_reviews CASCADE;


CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  CONSTRAINT UC_User UNIQUE (email)
);


CREATE TABLE quizzes (
  id SERIAL PRIMARY KEY NOT NULL,
  creator_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  type VARCHAR(255) NOT NULL,
  public BOOLEAN NOT NULL DEFAULT TRUE,
  thumbnail_url VARCHAR(255) NOT NULL
);


CREATE TABLE questions (
  id SERIAL PRIMARY KEY NOT NULL,
  quiz_id INTEGER REFERENCES quizzes(id) ON DELETE CASCADE,
  description TEXT NOT NULL,
  answer_one VARCHAR(255) NOT NULL,
  answer_two VARCHAR(255) NOT NULL,
  answer_three VARCHAR(255) NOT NULL,
  answer_four VARCHAR(255) NOT NULL,
  correct_answer SMALLINT NOT NULL
);


CREATE TABLE results (
  id SERIAL PRIMARY KEY NOT NULL,
  player_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  question_id INTEGER REFERENCES questions(id) ON DELETE CASCADE,
  chosen_answer SMALLINT NOT NULL
);


CREATE TABLE quiz_reviews (
  id SERIAL PRIMARY KEY NOT NULL,
  quiz_id INTEGER REFERENCES quizzes(id) ON DELETE CASCADE,
  player_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  rating SMALLINT NOT NULL DEFAULT 0
);
